version: 2

sources:
  - name: test
    description: "sample data"
    database: test
    schema: public
    tables:
      - name: team_locations
        description: '{{ doc("team_locations") }}'
      - name: example_teams
        description: '{{ doc("example_teams") }}'
      - name: car_color
        description: '{{ doc("car_color") }}'
      - name: car_type
        description: '{{ doc("car_type") }}'
      - name: products
        description: '{{ doc("products") }}'
      - name: id
        description: '{{ doc("id") }}'
      - name: date
        description: '{{ doc("date") }}'

models:
  - name: products
    description: '{{ doc("products") }}'
